script: make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: bmZEHXhlKk4gb0K6hjC2YKw2s1reMF4m5QZuK4nozlfLBXEH6uwqpgenjmX/ElFn7P+VIQKX8OGOhltiHMFp2iM3f9kDZABjIgXjxVbr+wKnRtR3ogHZLWHCWvVhPbpYYfEfeJYlvQuYnds+PoHI0gJWzz0G/zFndw1I3qaWDr8=
  app: akatsuki-presentation-stub01
  on:
    repo: arrancar-technology/akatsuki-presentation-stubulator
    branch: develop
